"""add_booking_tours

Revision ID: 8726ca590da3
Revises: 39e166939235
Create Date: 2024-12-14 23:34:33.768685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8726ca590da3'
down_revision: Union[str, None] = '39e166939235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tours',
    sa.Column('tour_id', sa.UUID(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('transport', sa.String(), nullable=False),
    sa.Column('hotel', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('tour_id')
    )
    op.create_index(op.f('ix_tours_tour_id'), 'tours', ['tour_id'], unique=False)
    op.create_table('bookings',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('tour_id', sa.UUID(), nullable=False),
    sa.Column('booking_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.tour_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_index(op.f('ix_bookings_booking_id'), 'bookings', ['booking_id'], unique=False)
    op.add_column('user', sa.Column('full_name', sa.String(), nullable=False))
    op.add_column('user', sa.Column('birth_date', sa.Date(), nullable=False))
    op.add_column('user', sa.Column('passport_data', sa.String(), nullable=False))
    op.add_column('user', sa.Column('phone_number', sa.String(), nullable=False))
    op.add_column('user', sa.Column('card_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'card_number')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'passport_data')
    op.drop_column('user', 'birth_date')
    op.drop_column('user', 'full_name')
    op.drop_index(op.f('ix_bookings_booking_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_tours_tour_id'), table_name='tours')
    op.drop_table('tours')
    # ### end Alembic commands ###
