"""removed_null_constraints

Revision ID: f4a0071dc0b9
Revises: 8726ca590da3
Create Date: 2024-12-15 01:14:13.013411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4a0071dc0b9'
down_revision: Union[str, None] = '8726ca590da3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'birth_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('user', 'passport_data',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'passport_data',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'birth_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('user', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
